version: "3"
services:
  chromedriver:
    image: robcherry/docker-chromedriver
    privileged: true
    restart: always
    environment:
      - CHROMEDRIVER_WHITELISTED_IPS=''
    # ports:
    #   - '4444:4444'
    networks:
      - default
  selenium-side-runner:
    image: nixel2007/docker-selenium-side-runner
    # build:
    #   context: .
    volumes:
      - './selenium_tests:/sides'
      - './selenium_tests/out:/root/out'
    networks:
      - default

networks:
  default:
    external:
      name: mark_demo_frontend_network


